default_context:
  chart_name: "controller"
  chart_version: "0.2.16"
  need_dep_chart: "no"
  include_service: "yes"
  service_name: "controller-communication-dsl"
  service_image_repo: "registry.apps.eo4eu.eu/eo4eu/eo4eu-inference-server/controller"
  service_image_tag: "bd97733c9083738dece5a039d3ac19ba41cd10b3"
  service_image_pull_policy: "Always"
  service_image_secret: "controller-registry"
  service_container_port: "8080"
  service_environment_label: "production"
  service_service_label: "Inference_Server"
  service_component_label: "controller"
  include_namespace: "yes"
  include_kafka_source: "yes"
  include_rbac: "yes"
  kafka_source_name: "kafka-source-controller"
  kafka_source_endpoint: "kafka-external.apps.eo4eu.eu:9092"
  include_external_registry_secret: "yes"
  external_registry_secret_name: "controller-registry"
  k8s_registry_secret_name: "controller-registry"
  external_registry_secret_data:
    "data": [
      {
        secret_key: "dockerconfigjson",
        vault_secret_key: "eo4eu-cicd/registry_pull_secret/eo4eu-inference-server/controller",
        vault_secret_property: ".dockerconfigjson"
      }
    ]